### ISSUE TITLE
Sample playbook makes nodes seed onto themselves only and cluster never forms

### ISSUE THREAD

**Issue by aijanai** [locp/ansible-role-cassandra#93]
**Describe the bug**
The line `- seeds: "{{ ansible_default_ipv4.address }}"` makes every node add itself as a seed and nothing else. Therefore, the cluster never forms because there is no shared point of contact between the nodes.

**To Reproduce**

```
- name: Example Playbook for the locp.cassandra Role

  hosts: cassandra

  remote_user: root

  vars:
    cassandra_configuration:
      authenticator: PasswordAuthenticator
      cluster_name: MyCassandraCluster
      commitlog_directory: /data/cassandra/commitlog
      commitlog_sync: periodic
      commitlog_sync_period_in_ms: 10000
      data_file_directories:
        - /data/cassandra/data
      endpoint_snitch: GossipingPropertyFileSnitch
      hints_directory: "/data/cassandra/hints"
      listen_address: "{{ ansible_default_ipv4.address }}"
      partitioner: org.apache.cassandra.dht.Murmur3Partitioner
      saved_caches_directory: /data/cassandra/saved_caches
      seed_provider:
        - class_name: "org.apache.cassandra.locator.SimpleSeedProvider"
          parameters:
            - seeds: "{{ ansible_default_ipv4.address }}"
      start_native_transport: true
    cassandra_configure_apache_repo: true
    # Create an alternative directories structure for the Cassandra data.
    # In this example, the will be a directory called /data owned by root
    # with rwxr-xr-x permissions.  It will have a series of sub-directories
    # all of which will be defaulted to being owned by the cassandra user
    # with rwx------ permissions.
    cassandra_directories:
      root:
        group: root
        mode: "0755"
        owner: root
        paths:
          - /data
      data:
        paths:
          - /data/cassandra
          - /data/cassandra/commitlog
          - /data/cassandra/data
          - /data/cassandra/hints
          - /data/cassandra/saved_caches
    cassandra_regex_replacements:
      - path: cassandra-env.sh
        line: 'MAX_HEAP_SIZE="512M"'
        regexp: '^#MAX_HEAP_SIZE="4G"'
      - path: cassandra-env.sh
        line: 'HEAP_NEWSIZE="100M"'
        regexp: '^#HEAP_NEWSIZE="800M"'
      - path: cassandra-rackdc.properties
        line: 'dc=DC1'
        regexp: '^dc='
      - path: cassandra-rackdc.properties
        line: 'rack=RACK1'
        regexp: '^rack='
    cassandra_repo_apache_release: 311x

  roles:
    - role: locp.cassandra
```

**Expected behaviour**
I would expect a lab with 3 or more machines to form into a cluster (sample Vagrantfile included)
```
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

  config.vm.define :server1 do |server|
    server.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      server.vm.network :private_network, ip: "192.168.42.101"
    end
  end

  config.vm.define :server2 do |server|
    server.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      server.vm.network :private_network, ip: "192.168.42.102"
    end
  end

  config.vm.define :server3 do |server|
    server.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      server.vm.network :private_network, ip: "192.168.42.103"
    end
  end


end
```
**Screenshots**
`nodetool status` on each node reports pnly the IP of the node it has been executed on.

**Versions (please complete the following information):**
- Ansible version: 2.2.7
- Role version: develop 9872568
- Python version: 3.7.4 Anaconda
